### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by thrawny** [airbnb/hypernova-node#6]
After upgrading to 1.0.2, server rendering now works. However I still get an error on every request.
Source file not built properly?

```js
Requesting MyComponent.js { name: 'Stranger' }
TypeError: Object.values is not a function
    at /Users/thrawn/Stuff/js/hypernova/node_modules/hypernova-client/lib/index.js:194:22
    at /Users/thrawn/Stuff/js/hypernova/node_modules/hypernova-client/lib/index.js:217:14
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by ljharb** [comment]
Oops, our code was assuming https://www.npmjs.com/package/airbnb-js-shims was in use. We'll get a fix out this weekend.
